########## Pull ##########
FROM osrf/ros:melodic-desktop-full

# Arguments
ARG USER=initial
ARG GROUP=initial
ARG UID=1000
ARG GID=${UID}
ARG SHELL=/bin/bash

# Replace apt urls
RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list

# Install packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget curl ssh \
    zsh terminator gnome-terminal git vim tig \
    dbus-x11 libglvnd0 libgl1 libglx0 libegl1 libxext6 libx11-6 \
    python-catkin-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

# ref https://mokuzine.net/ubuntu-apt-util-warn/
ENV DEBCONF_NOWARNINGS=yes 

# Setup users and groups
RUN groupadd --gid ${GID} ${GROUP} \
  && useradd --gid ${GID} --uid ${UID} -ms ${SHELL} ${USER} \
  && mkdir -p /etc/sudoers.d \
  && echo "${USER}:x:${UID}:${UID}:${USER},,,:$HOME:${shell}" >> /etc/passwd \
  && echo "${USER}:x:${UID}:" >> /etc/group \
  && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USER}" \
  && chmod 0440 "/etc/sudoers.d/${USER}"

# copy entrypoint
COPY entrypoint.bash /entrypoint.bash
RUN chmod 777 /entrypoint.bash

# setup terminator config
RUN mkdir -p /home/${USER}/.config/terminator
COPY config/terminator/config /home/${USER}/.config/terminator
RUN sudo chown -R ${USER}:${GROUP} /home/${USER}/.config

# Switch user to ${USER}
USER ${USER}

# Make SSH available
EXPOSE 22

######### initial position ##########
WORKDIR /home/${USER}

##RUN sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
##RUN sudo apt install curl
##RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

RUN sudo apt update
# setup move_base packages
RUN sudo apt-get install -y ros-melodic-amcl ros-melodic-move-base ros-melodic-map-server ros-melodic-dwa-local-planner

# setup tutlebot packages
RUN sudo apt-get install -y ros-melodic-turtlebot3-*

# setup rosserial
RUN sudo apt-get install -y ros-melodic-rosserial-arduino
RUN sudo apt-get install -y ros-melodic-rosserial

## sudo apt_get install tf2_tools
## sudo apt install ros-melodic-geometry2
## sudo apt-get install -y evince

# setup catkin_ws
RUN mkdir -p catkin_ws/src

# CMD ["terminator"]
ENTRYPOINT ["/entrypoint.bash", "terminator"]
